### ISSUE TITLE
Default for ID of CompositeCluster instance confusing

### ISSUE THREAD

**Issue by turkenh** [upbound/platform-ref-aws#34]
I've created a `CompositeCluster` instance with all defaults and it looks like I am not alone. 

This caused conflicting resources with another instance in the same AWS account, e.g. multiple eks `Cluster` instances with same external-name.

```
   conditions:
    - lastTransitionTime: "2020-11-06T22:58:44Z"
      message: "update failed: cannot update EKS cluster configuration: InvalidParameterException:
        subnetIds and securityGroupIds cannot be updated.\n\tstatus code: 400, request
        id: 78599dbe-27b1-4e0f-bfeb-5db6264c1a2c"
      reason: ReconcileError
      status: "False"
      type: Synced
```

We should not have [default for id field](https://github.com/upbound/platform-ref-aws/blob/b843c8957eb716cfe51aae667ba3fcec14a1ba3c/cluster/definition.yaml#L18) and ideally have a way to warn user that selected id is in use.
