### ISSUE TITLE
v0.1.1 PostgreSQLInstance spec.writeConnectionSecretToRef.namespace required but not allowed

### ISSUE THREAD

**Issue by prasek** [upbound/platform-ref-aws#43]
platform-ref-aws v0.1.1 is giving me this from the UI and with the examples/postgres-claim.yaml

```
31s         Warning   ComposeResources                  compositepostgresqlinstance/testdb-6grsv                                
                cannot render composed resource at index 1: cannot use dry-run create to name composed resource: RDSInstance.database.aws.crossplane.io "testdb-6grsv-p94gr" is invalid: spec.writeConnectionSecretToRef.namespace: Required value
4s          Warning   ComposeResources                  compositepostgresqlinstance/testdb-6grsv                                                 cannot render composed resource at index 1: cannot use dry-run create to name composed resource: RDSInstance.database.aws.crossplane.io "testdb-6grsv-fnb7w" is invalid: spec.writeConnectionSecretToRef.namespace: Required value
```

when I try to specify it on the claim:
```
apiVersion: aws.platformref.crossplane.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: my-db
  namespace: team-ns
spec:
  parameters:
    storageGB: 20
    networkRef:
      id: platform-ref-aws-network
  writeConnectionSecretToRef:
    name: my-db-conn
    namespace: team-ns
```

it says namespace doesn't exist on the claim kind when I apply it
```
k apply -f examples/postgres-claim.yaml
error: error validating "examples/postgres-claim.yaml": error validating data: ValidationError(PostgreSQLInstance.spec.writeConnectionSecretToRef): unknown field "namespace" in io.crossplane.platformref.aws.v1alpha1.PostgreSQLInstance.spec.writeConnectionSecretToRef; if you choose to ignore these errors, turn validation off with --validate=false
```

and looking at the CRD it's not present:
`k get crds postgresqlinstances.aws.platformref.crossplane.io -o yaml`
```
writeConnectionSecretToRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
```
